### ISSUE TITLE
登录异常

### ISSUE THREAD

**Issue by q2316367743** [blossom-editor/blossom#10]
![Snipaste_2023-09-28_11-25-43](https://github.com/blossom-editor/blossom/assets/49052369/1f71b0ec-9469-4116-b215-122aa76a616d)
不仅报空指针
![图像_2023-09-28_113051473](https://github.com/blossom-editor/blossom/assets/49052369/eeb59fdc-50a4-428b-b550-1e9cc74f0970)
登陆成功后，数据获取不到

**Comment by xiaozzzi** [comment]
方便的话请提供一下错误日志帮助更好的排查，日志在后台应用的logs目录下

**Comment by q2316367743** [comment]
有邮箱吗，我发你邮箱

**Comment by xiaozzzi** [comment]
> 有邮箱吗，我发你邮箱

491548320@qq.com

**Comment by q2316367743** [comment]
发给你了
