### ISSUE TITLE
【功能需求】希望可以优化备份

### ISSUE THREAD

**Issue by xkloveme** [blossom-editor/blossom#100]
![image](https://github.com/blossom-editor/blossom/assets/29595042/6781d0c0-6e2b-4626-a40e-937459cc096a)
 1.希望备份可以指定时间和周期，每天固定备份不会覆盖占用存储越来越大
 2.希望可以直接备份文件夹而不是 zip

**Comment by xiaozzzi** [comment]
1. 备份时间暂不能指定，但可以设置备份文件的保留时间，默认是7天前的备份会删除，不会无限保留占满磁盘

2. 备份的方式应该不会修改，大多数人的需求是备份压缩包，并且压缩包有利于从客户端下载
