### ISSUE TITLE
博客页代码未对齐

### ISSUE THREAD

**Issue by straysh** [blossom-editor/blossom#106]
后台编辑与预览区域，代码是对齐的
![Screenshot_select-area_20240404194824](https://github.com/blossom-editor/blossom/assets/3816071/f4d3b211-15ae-457e-bc27-c70c212afab5)

但文章发布后，在博客页没有对齐
![image](https://github.com/blossom-editor/blossom/assets/3816071/da96e4ca-160e-4274-9bde-0aea6c9108dd)

**Comment by xiaozzzi** [comment]
该问题已在[v1.14.0](https://github.com/blossom-editor/blossom/releases/tag/v1.14.0)版本中修复。
