### ISSUE TITLE
Home的天气可以关闭不显示吗？

### ISSUE THREAD

**Issue by DHS1001** [blossom-editor/blossom#107]
非常感谢开发和分享blossom，在使用过程中发现天气部分没有相关的设置来控制显示或者关闭。
不知道是否有可能在设置中加入相应的开关呢？
谢谢

**Comment by xiaozzzi** [comment]
![image](https://github.com/blossom-editor/blossom/assets/42293085/f39bb890-2641-4fe6-92f6-99da52e11d60)
关闭后页面会变成这样，所以在找到能保证页面美观和完整的方法之前，应该无法加入关闭功能了

不知你是否有什么好的方法能解决关闭后的页面排版吗？

**Comment by DHS1001** [comment]
> 不知你是否有什么好的方法能解决关闭后的页面排版吗？

非常感谢回复，
如果能把 头像 和 笔记本电脑 都一起关闭是否可行呢？

**Comment by xiaozzzi** [comment]
这样也会影响整体布局，整体都要重新设计
![image](https://github.com/blossom-editor/blossom/assets/42293085/9fa4ea95-63bd-49cd-a85a-047c95db60ed)

**Comment by DHS1001** [comment]
试了一下把Good Afternoon也去掉，然后把“字数统计”高度改成65。
把 .main .chart-container 的高度 改成 height: calc(100% **- 5px**);
布局视乎就整齐了。

![image](https://github.com/blossom-editor/blossom/assets/104676399/9058f73b-927f-48fb-bf16-8e222ca8dec7)

**Comment by xiaozzzi** [comment]
单从关闭天气这一行来说是这样的，但每个人期望首页展示的内容都不相同，所以说很难只做一个关闭天气的功能。

如果要做的话肯定是首页尽量实现自定义布局，但这样在设计和开发上都有很多工作要做。

总之太过个性化的需求很那实现，也会让整体变的臃肿

**Comment by DHS1001** [comment]
> 单从关闭天气这一行来说是这样的，但每个人期望首页展示的内容都不相同，所以说很难只做一个关闭天气的功能。
> 
> 如果要做的话肯定是首页尽量实现自定义布局，但这样在设计和开发上都有很多工作要做。
> 
> 总之太过个性化的需求很那实现，也会让整体变的臃肿

的确如此，谢谢啦
