### ISSUE TITLE
字数统计编辑 中的月份选择的月份超出了右边边界

### ISSUE THREAD

**Issue by DHS1001** [blossom-editor/blossom#108]
字数统计编辑 中的月份选择的月份超出了右边边界

系统：Win10
浏览器：Edge
显示比例：100%

![image](https://github.com/blossom-editor/blossom/assets/104676399/a0605f41-99c7-4a62-adc7-48b79f2d4831)

**Comment by xiaozzzi** [comment]
问题已修复，下版本发布
