### ISSUE TITLE
[功能需求] Todo待办事项能否重复或循环

### ISSUE THREAD

**Issue by Hypnos3420** [blossom-editor/blossom#109]
1、希望能添加有固定周期的每日Todo，或者已有的Todo可以复制、拖拽，或者给个模板然后拖到日历上建立对应日期的Todo？
2、Editor的工具里能否增加1个改变文字颜色的功能和，刚开始接触markdown，黑白实在有点不习惯，目前是复制<font>来写……
3、快捷键是否能自定义？
4、Plan的功能很棒，就是跨月的进度没有名字，能否像Todo一样有个总览？
![1](https://github.com/blossom-editor/blossom/assets/24874955/d8421357-1c9c-4772-8294-7be92689286e)
5、Plan里的计划怎么删除……

**Comment by xiaozzzi** [comment]
1. todo 目前可以点击红框的转移事项将 todo 转移至其他日期，目前 todo 和 plan 还无法关联在一起。如果有长期的事项，例如一段长时间的项目，可以选择使用绿色框的阶段性事项。
![image](https://github.com/blossom-editor/blossom/assets/42293085/1de8ab4d-18d7-426a-a01b-02adb353e426)
2. 目前无法改变字体颜色。
3. 目前无法自定义快捷键。
4. 跨月的可以点击任意一天查看详情，没有名字我看看后续如何优化。
5. 鼠标移动至plan的最后一天上会显示删除按钮

**Comment by Hypnos3420** [comment]
感谢解惑
