### ISSUE TITLE
客户端异常

### ISSUE THREAD

**Issue by q2316367743** [blossom-editor/blossom#11]
![Snipaste_2023-09-28_11-28-35](https://github.com/blossom-editor/blossom/assets/49052369/108a4f7e-263f-4bfe-8f3f-563813957a6a)
客户端退出时，未退出全部进程，导致第二次无法打开，需要杀死这几个进程才能重新打开

**Comment by xiaozzzi** [comment]
右上角关闭默认是关闭窗口，并不是退出应用。窗口关闭可以在托盘中重新打开。关闭应用可以邮件点击托盘图标
