### ISSUE TITLE
浏览器临时访问页面没有受到博客配置的影响

### ISSUE THREAD

**Issue by klaus-cicd** [blossom-editor/blossom#110]
背景：
已在编辑器博客配置内开启了“是否显示文章标题”和“开启文章水印”，博客内显示正常
<img width="572" alt="image" src="https://github.com/blossom-editor/blossom/assets/81892709/69f80a23-a4cc-433e-aee7-992c6f219bd6">
![image](https://github.com/blossom-editor/blossom/assets/81892709/7024b7c2-f8ad-41f3-8ccf-e50372f0d705)

问题：
使用“浏览器临时访问”的方式查看文章，缺少文章标题和水印背景
<img width="180" alt="image" src="https://github.com/blossom-editor/blossom/assets/81892709/15fd289b-197a-48a1-a067-eb2fd1bc989b">
![image](https://github.com/blossom-editor/blossom/assets/81892709/09e01c03-88da-47c7-9f4e-71dedebe62f6)

**Comment by xiaozzzi** [comment]
临时访问目前还不受博客配置影响，下版本我尽量支持一下

**Comment by xiaozzzi** [comment]
该功能已在 [v1.16.0](https://github.com/blossom-editor/blossom/releases/tag/v1.16.0) 版本中支持
