### ISSUE TITLE
在没有登录的情况下，上传的按钮也可按？

### ISSUE THREAD

**Issue by DHS1001** [blossom-editor/blossom#111]
在没有登录的情况下，发现上传的按钮也可以按。
不知道这个是否是个bug还是设计成这样的呢？
谢谢

![image](https://github.com/blossom-editor/blossom/assets/104676399/0ae7a240-1112-4fea-b8de-74836504b105)

**Comment by xiaozzzi** [comment]
可以点击，但是未登录的情况下上传会失败

**Comment by DHS1001** [comment]
谢谢解惑 ：）
