### ISSUE TITLE
希望可以对图片功能加强

### ISSUE THREAD

**Issue by zzkuner** [blossom-editor/blossom#113]
1.首先是希望可以加入，自动把第三方的图片存到本地，防止图片丢失
2.希望实现picgo这种图床功能，可以连接对象存储实现：图像的本地和云端选择一个地方来存储
3.自动重命名这个功能很需要啊呜呜呜

**Comment by xiaozzzi** [comment]
第一第二点涉及到比较多的开发内容和测试工作，所以短期可能没那么多精力开发
第三点可以在客户端设置中开启
![image](https://github.com/blossom-editor/blossom/assets/42293085/060644a0-0284-431a-a245-d13da8da0258)

**Comment by zzkuner** [comment]
明白了，谢谢

**Comment by zzkuner** [comment]
还有想请问默认上传的图片的/pic/home/bl/img/U1/链接，中间这个home/bl/img怎么修改呢

**Comment by xiaozzzi** [comment]
> 还有想请问默认上传的图片的/pic/home/bl/img/U1/链接，中间这个home/bl/img怎么修改呢

可以修改参数`--project.iaas.blos.default-path`，具体可以查看文档：https://www.wangyunf.com/blossom-doc/guide/deploy/backend-props.html#props-iaas-blos

**Comment by zzkuner** [comment]
好的，感谢
