### ISSUE TITLE
申请加一个文章或者专题提供单独一个页面吗，不要和我其他公开的文章一起显示

### ISSUE THREAD

**Issue by zzkuner** [blossom-editor/blossom#115]
可以申请加一个文章或者专题单独一个页面吗，不要和我其他公开的文章一起显示
有的时候只希望一部分只看到这篇文章或者这个专题

**Comment by xiaozzzi** [comment]
你是指博客还是客户端呢？

单独页面是展示在哪里？

最好能更详细的描述一下期望的功能，例如操作步骤，按钮位置，页面如何展示等
