### ISSUE TITLE
大佬，我想问下，有计划把接口封装成API吗，以及加入记账的功能吗

### ISSUE THREAD

**Issue by ZZLinvec** [blossom-editor/blossom#116]
我想问下，有计划把笔记和todo封装成API接口，以及加入记账的功能吗
原因如下
1）把笔记和todo封装成API，我是想着能够通过AI工作流直接把一些好文章直接收录到笔记里。
2）加入记账的功能是想着一个软件把知识资源和金钱资源一起规划总结起来

**Comment by xiaozzzi** [comment]
所有接口是有的API文档的：https://github.com/blossom-editor/blossom/tree/dev/doc/backend-api

记账功能恐怕不会增加

**Comment by ZZLinvec** [comment]
大佬，那这个API说明文档是需要单独运行吗，还是部署blossom后，访问对应的路径即可？我找了半天似乎没有找到访问的路径。

**Comment by ZZLinvec** [comment]
好吧，我把代码clone到本地，然后用浏览器打开就看到了，哈哈哈哈，我本来是用docker部署的，就是不知道说明文档有没有运行起来。哈哈哈哈
