### ISSUE TITLE
更新1.16.0后，博客客户端提示网络错误

### ISSUE THREAD

**Issue by greentree1321** [blossom-editor/blossom#117]
我用自己部署的博客客户端，更新最新的1.16后，博客客户端连不上服务器。笔记客户端可正常链接。

**Comment by xiaozzzi** [comment]
单独部署的博客更新后有没有修改服务器的地址？
![image](https://github.com/blossom-editor/blossom/assets/42293085/5de08f9e-e04e-4996-ac12-292d6b34c330)

最好能提供浏览器控制台的截图信息

**Comment by greentree1321** [comment]
确实是博客配置文件忘记设置后台地址了，谢谢。
