### ISSUE TITLE
使用v1.16.0创建计划保存后变成前一天

### ISSUE THREAD

**Issue by wasonic** [blossom-editor/blossom#119]
系统环境：win11
客户端版本：v1.16.0
问题描述：使用plan功能创建一个计划，保存后日期变成了前一天的，比如创建时选择日期为2024-04-25 09:00:00 至 2024-04-25 18:00:00，保存之后会变成 2024-04-24 09:00:00 至 2024-04-24 18:00:00 的

**Comment by xiaozzzi** [comment]
这个一般和时区有关，服务端也是在本地 windows 吗？

服务端的默认时区是东八区，你的位置是否在国内呢？

**Comment by wasonic** [comment]
客户端是在win11上，服务器端是docker部署在linux系统上的，位置是国内的，时区是东八区，使用 date 命令输出 Thu Apr 25 04:36:58 PM CST 2024，和北京时间并没有偏差

**Comment by wasonic** [comment]
> 这个一般和时区有关，服务端也是在本地 windows 吗？
> 
> 服务端的默认时区是东八区，你的位置是否在国内呢？

找到问题所在了，示例说明中配置MYSQL连接配置`serverTimezone=GMT`，改成`serverTimezone=Asia/Shanghai`就没问题了
