### ISSUE TITLE
图片浏览卡顿

### ISSUE THREAD

**Issue by Hanserwei** [blossom-editor/blossom#120]
使用群晖docker部署，在图片一栏上传约678Mb图片，然后发现浏览图片十分卡顿，由于是局域网，应该不是网络的问题。又遇到类似情况的朋友吗？

**Comment by jesse-zhangh** [comment]
图片无法显示
![image](https://github.com/blossom-editor/blossom/assets/87465352/51736dc3-872e-4407-9634-8e1d16fda66d)

部署方式：docker compose
客户端：Windows客户端
网页客户端也无法显示图片
