### ISSUE TITLE
换行不对

### ISSUE THREAD

**Issue by maxiaogood** [blossom-editor/blossom#127]
![image](https://github.com/blossom-editor/blossom/assets/65268883/2dc18b27-680e-45a6-9967-04a3f96bc3dd)

**Comment by maxiaogood** [comment]
![image](https://github.com/blossom-editor/blossom/assets/65268883/124add09-a55d-468c-9c27-1afd3db8dafe)

**Comment by xiaozzzi** [comment]
这是markdown的规范，要换行需要隔一个空行

**Comment by maxiaogood** [comment]
OK，谢谢
