### ISSUE TITLE
编辑页面上传图片希望增加重命名功能

### ISSUE THREAD

**Issue by Fansirsqi** [blossom-editor/blossom#128]
有没有在编辑文章的页面直接上传至服务器图片的方法，按ctrl+v可以上传剪切板里的图片，但是不会自动重命名
![image](https://github.com/blossom-editor/blossom/assets/38542005/801d4c94-611c-4811-8c4a-9597ba28d87f)

**Comment by xiaozzzi** [comment]
客户端的设置中，详见 https://www.wangyunf.com/blossom-doc/guide/deploy/faq.html#pic-exist
