### ISSUE TITLE
群号及开发者联系方式

### ISSUE THREAD

**Issue by xiaozzzi** [blossom-editor/blossom#13]
有需要的可以加群：
一群：`522359970`
二群：`921906098`
三群：`749721525`

**Comment by li-guohao** [comment]
> 522359970

建群了都不通知我下QAQ

**Comment by xiaozzzi** [comment]
> > 522359970
> 
> 建群了都不通知我下QAQ

群今天刚建，因为放假了就没打扰你，下次一定先通知你哈哈，节日快乐！

**Comment by li-guohao** [comment]
节日快乐

**Comment by niquxx** [comment]
三群又满了，什么时候开四群呀

**Comment by T1anjiu** [comment]
> 三群又满了，什么时候开四群呀

四群开了，你看一下介绍

**Comment by T1anjiu** [comment]
> 三群又满了，什么时候开四群呀
差不多一个月之前更新的
