### ISSUE TITLE
后台部署不需要博客和后台页面，如何能关闭

### ISSUE THREAD

**Issue by dislazy** [blossom-editor/blossom#131]
作者您好，blossom是一个非常优秀的开源笔记和博客平台，我目前主要是自己部署了后台和独立部署了后台管理端，所以想关闭后台中自带的/blog/#/home和/editor/#/settingindex，来减少数据泄露，不知道有什么好的方式，或者加个配置，感谢作者

**Comment by xiaozzzi** [comment]
目前没有配置可以关闭。

如果通过容器部署，可以通过挂载文件的方式将后台自带的页面文件清空。

或者在反代中修改对应路径的跳转。

这两种方法可以禁用掉自带页面的访问。

**Comment by dislazy** [comment]
> 目前没有配置可以关闭。
> 
> 如果通过容器部署，可以通过挂载文件的方式将后台自带的页面文件清空。
> 
> 或者在反代中修改对应路径的跳转。
> 
> 这两种方法可以禁用掉自带页面的访问。

我在容器中一直没有找到对应文件的目录，方便告知不

**Comment by xiaozzzi** [comment]
/application/BOOT-INF/classes/static/blog

**Comment by dislazy** [comment]
感谢大佬
