### ISSUE TITLE
【建议】希望在编辑器预览侧加入内容编辑侧的定位功能

### ISSUE THREAD

**Issue by fenbays** [blossom-editor/blossom#135]
如题，目前右侧预览器滚动时左侧编辑器内容是不会同步滚动的，内容多时无法快速地在左侧找到相应的编辑位置。

建议可以通过双击预览侧的指定目录，定位并滚动左侧编辑器到对应的内容位置。

**Comment by xiaozzzi** [comment]
这项功能在计划中，会在以后的版本中优化
