### ISSUE TITLE
【功能建议】

### ISSUE THREAD

**Issue by KevinR10** [blossom-editor/blossom#138]
请问新建计划/任务的界面，是否可以添加“创建下一条”的按钮，点击该按钮，保存此条数据并以当前数据为模板，填充至下一计划/任务，方便建立多条代办/计划。
![image](https://github.com/user-attachments/assets/6e2cfe18-4b45-4360-9a67-536dc8499fcc)

**Comment by xiaozzzi** [comment]
我记录一下，作为以后的优化项
