### ISSUE TITLE
【功能建议】提几个小小的优化点

### ISSUE THREAD

**Issue by yanshifly** [blossom-editor/blossom#139]
* 能否增加让设定的计划在到达前通过邮件通知或其他形式进行通知
* 可以通过更改设定的方式将自动备份模式切换为本地Markdown
* 编辑菜单中增加左侧文件栏隐藏的按钮（屏幕小导致编辑区域很窄，虽然有快捷键关闭但是有时候按快捷键比较麻烦）

**Comment by xiaozzzi** [comment]
我记录一下，作为后续的优化项
