### ISSUE TITLE
【功能建议】小建议

### ISSUE THREAD

**Issue by 404-xianjin** [blossom-editor/blossom#140]

**Comment by 404-xianjin** [comment]
![image](https://github.com/user-attachments/assets/6c0dbff9-30a9-4dcf-b949-f7f339c50e97)
- 另外就是想确认下，这个地方的设置是起什么作用的？我设置完以后不确定在哪里检查效果呢

**Comment by xiaozzzi** [comment]
颜色目前只有专题文件夹配置有效，会显示在博客首页
