### ISSUE TITLE
可否像思源笔记一样，开发一些高级功能一次性付费

### ISSUE THREAD

**Issue by zzkuner** [blossom-editor/blossom#146]
可否像思源笔记一样，开发一些高级功能一次性付费，这样也能帮助作者生存，也可以帮助项目可以快速迭代

**Comment by T1anjiu** [comment]
项目初心就是要和思源这种不同，做一个不一样的免费的笔记软件。

如果你有高级功能的建议可以提出来，我们可以在后续更新进行添加。

:)🌸🌸🌸
