### ISSUE TITLE
[建议]关于Editor功能的文档列表界面的一些建议

### ISSUE THREAD

**Issue by Zheny918** [blossom-editor/blossom#15]
1、建议新增完文件夹或者文章后，列表可以自动刷新；
2、建议新增文件夹或者文章时，可以根据选择的类型增加默认的图标，比如选择文件夹默认一个文件夹的图标，选择文章则默认一个文档的图标；如果需要修改，则保持现在的功能，允许自行调整；（目前如果默认不设置图标的话，在列表中分不清是文件夹还是文章）
![image](https://github.com/blossom-editor/blossom/assets/21190506/4592a3eb-3c65-49e2-9f89-e6af360c1813)

**Comment by xiaozzzi** [comment]
好的，预计下个版本就支持🎉
我自己有时也分不清是文章还是文件夹

**Comment by xiaozzzi** [comment]
已在 v1.6.0 版本支持
