### ISSUE TITLE
[功能建议]MacOS中使用Edge访问文章编辑器粘贴截图上传功能优化

### ISSUE THREAD

**Issue by Relaxself** [blossom-editor/blossom#155]
首先，非常感谢 大大 的辛苦付出，使得我有机会使用这个一体化的博客+内容管理系统。

我目前使用的方案是：
使用家里Nas里的docker-compose部署了这个应用，使用FRP开放到云服务器上。
日常操作端是 MacOS Ventra + 微软Edge浏览器，在线访问与编辑

目前，当我使用截图工具截图后，在编辑器里使用 Command+V 粘贴，编辑器会自动上传图片到目录中并进行引用
但是，上传组件会默认将图片上传成 image.png 的名称，导致第二次截图粘贴它就会重名！

我有一个建议，看看大大是否可以将此类 截图/粘贴 的图片文件，自动在文件名后增加 yyyyMMddHHmmss来防止重复呢？

如果能接受这个建议，大概会在什么时间？
如果没有这个计划，我自己想想办法fork一个版本吧。

谢谢
<img width="704" alt="image" src="https://github.com/user-attachments/assets/c31394af-ce14-4ad7-826a-f7c9c02401a2">

**Comment by NJYZ-96** [comment]
看看这个能否解决你的问题：

https://www.wangyunf.com/blossom-doc/guide/deploy/faq.html#pic-exist

![截图_20240922215258](https://github.com/user-attachments/assets/cfe6f5e6-1fb5-4a57-a496-dc89a057b43c)

**Comment by Relaxself** [comment]
> 看看这个能否解决你的问题：
> 
> https://www.wangyunf.com/blossom-doc/guide/deploy/faq.html#pic-exist
> 
> ![截图_20240922215258](https://private-user-images.githubusercontent.com/125748593/369692525-cfe6f5e6-1fb5-4a57-a496-dc89a057b43c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDc4NzEsIm5iZiI6MTcyNzE0NzU3MSwicGF0aCI6Ii8xMjU3NDg1OTMvMzY5NjkyNTI1LWNmZTZmNWU2LTFmYjUtNGE1Ny1hNDk2LWRjODlhMDU3YjQzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwMzEyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWE2ZjIzOWM1YWIxZjc4NGNlYjgyN2E0ODNkOGFhYjkyNGM3NzZlMWRmMGVlZWFlNWI1ZTRkMTg3OTIwZGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MEO0LMCkPxJds9rtfO2R0rndKTpWudpcKEXA8s4sUSg)

感谢，已经解决了这个问题
