### ISSUE TITLE
关于文档工具栏功能建议

### ISSUE THREAD

**Issue by 2326671686** [blossom-editor/blossom#167]
1.标题功能，一级标题 二级标题...正文等等。现在每次要自己输入符号#
2.目录功能，现在目录是悬浮的，但是不能一键添加到文档中

**Comment by T1anjiu** [comment]
> 1.标题功能，一级标题 二级标题...正文等等。现在每次要自己输入符号#
> 2.目录功能，现在目录是悬浮的，但是不能一键添加到文档中

您说的这个第一个意见是不是希望是像wordpress他编辑器那样有一个通过点击设置1级标题，2级标题的功能？

**Comment by 2326671686** [comment]
> > 1.标题功能，一级标题 二级标题...正文等等。现在每次要自己输入符号#
> > 2.目录功能，现在目录是悬浮的，但是不能一键添加到文档中
> 
> 您说的这个第一个意见是不是希望是像wordpress他编辑器那样有一个通过点击设置1级标题，2级标题的功能？

是的
