### ISSUE TITLE
[建议]PLAN功能建议

### ISSUE THREAD

**Issue by Zheny918** [blossom-editor/blossom#17]
1、新增计划的界面，如果之前的计划设置了重复天数，即使新的计划没有勾选重复，依旧会生成重复的计划，就像下图一样
![image](https://github.com/blossom-editor/blossom/assets/21190506/45454d11-f226-435b-b690-6af2a2185a8a)

**Comment by xiaozzzi** [comment]
该功能已在 v1.6.0 版本更新
