### ISSUE TITLE
[建议&讨论]关于任务和计划的功能一些不成熟的想法

### ISSUE THREAD

**Issue by Zheny918** [blossom-editor/blossom#18]
目前TODO及PLAN功能是OK的，我觉得已经可以很好的管理每天的任务和计划，这里有一些不成熟的想法，可以讨论下。目前想到的有以下几点：
1、首先目前这样各自管理保留，并且作为默认的情况；然后新增plan计划新增可以选择关联对应的todo任务，或者todo任务新增的时候可以选择关联paln计划，这样可以实现计划和任务的关联性，计划作为目标，任务作为具体的过程；
2、任务和计划的新增界面，新增一个提醒时间，默认可以不选择，如果某个任务或者计划需要提醒的话可以维护提醒时间，调用系统的闹钟进行提醒或者弹框进行提醒；

**Comment by xiaozzzi** [comment]
1、目前打算把两个功能关联起来的，不过这项功能的优先级不高，后续要再进一步设计和考虑
2、提醒功能可以增加，计划中右上角会有一个消息汇总的功能，不过这个功能复杂度可大可小，想体验好一点的话还得多考虑考虑。

**Comment by Zheny918** [comment]
OKOK，期待后续的版本
