### ISSUE TITLE
[建议&讨论]关于导入导出支持更多格式

### ISSUE THREAD

**Issue by Zheny918** [blossom-editor/blossom#19]
目前导出可以支持导出为MD文件和HTML文件，但是导入的话只支持MD文件和TXT文件，比较单一，希望可以增加更多形式的导入导出，比如ZIP和MHT文件的导入，方便从其他笔记平台进行迁移；
MHT这种格式也是我最近发现的，为知笔记可以导出为MHT文件，这个文件的好处是他把笔记完整的导出为一个文件，这个文件里包含了所有文件及多媒体图片;
ZIP这种格式本质上是一个网页和一个资源包的合集，可以一次性将文章和图片进行导入；

当然，如果可以针对性的找几个其他笔记平台的导出格式进行匹配，那样更好了。比如常见的一些笔记平台：语雀、obsidian、思源、为知、有道、印象笔记、Notion，其他的一些开源笔记如trilium、Joplin等。

**Comment by Zheny918** [comment]
目前我在用的是trilium 笔记，他是导出的完整的ZIP格式，但是里面不止有网页和资源包，还有一些其他的文件用于控制样式的，就像下图
![image](https://github.com/blossom-editor/blossom/assets/21190506/6be67aa9-9fd7-4a4c-92fb-137f1625b59e)

这也是个不错的知识库笔记项目，但是功能比较单一，这个是笔记项目地址：https://github.com/zadam/trilium

**Comment by xiaozzzi** [comment]
Blossom 现在也支持把图片和文章一起导出为 zip，这个功能在备份里面，如果导出为 html 的话样式是写在 html 里的，这样分享的时候就只需要发送一个文件了，当然代价就是无法统一修改了。下面是一个示例
<img width="737" alt="{C8187E90-D2E9-412d-9C45-51B3753DB7A0}" src="https://github.com/blossom-editor/blossom/assets/42293085/1c9d8174-09f3-4ced-92b9-695d488b8132">

---

导入适配感觉这个工程太庞大了，很多商业化产品都很难做好。

导入图片和文章的zip可以考虑支持，但是一般来说如果是要支持大量文章及图片的批量导入，就要支持相关的批量删除，很多人第一次导入都很难对格式，或者存储位置等等百分白满意，然后调整起来就比较繁琐。所以导入和删除我都是用比较慎重的方式来处理的，而且考虑到个人服务器性能带宽都比较小，大批量的处理数据也可能会存在一些风险(比方说等待后台处理的过程中客户端出现超时，此时如果重复上传后的冲突问题等等)。

**Comment by Zheny918** [comment]
对了，建议支持导出为PDF和word文件，这个可能比较有用
