### ISSUE TITLE
[建议]颜色调整&代码行号展示

### ISSUE THREAD

**Issue by silas-wen** [blossom-editor/blossom#20]
1. 黑暗模式下，背景有点绿绿的，很多字体颜色还是灰色，很难看清，建议黑暗模式下优化字体/图标颜色进行优化 
![image](https://github.com/blossom-editor/blossom/assets/81892709/63935cc5-f3fa-4cba-99b9-fb4863cce579)
2. 希望可以展示代码块行号
3. 主题颜色可以增加一些选择，比如比较大众的天蓝

**Comment by xiaozzzi** [comment]
第二点已在 v1.7.0 版本支持

**Comment by xiaozzzi** [comment]
第三点已在 [v1.8.1](https://github.com/blossom-editor/blossom/releases/tag/v1.8.1) 版本支持
