### ISSUE TITLE
[BUG]新增文档后所在目录异常

### ISSUE THREAD

**Issue by rex-949** [blossom-editor/blossom#23]
操作如下：我先在a目录下的b文章编写保存后，去a的同级目录c目录下去导入文章c（此时a目录已经被我收缩了），再点击刷新，又定位到了之前的b目录下了（a目录被自动展开），但是其实我现在的工作区应该在c文章；
如果我选择在c目录下创建文章而不是导入文章，创建后不需要点击刷新就跳回b文章了

希望效果：1. 新增文章后，工作区定为新增的文章位置 2. 刷新列表之后，所在的工作区不变

**Comment by xiaozzzi** [comment]
感谢你反馈的问题！这个主要是因为当文档列表中发生增加或删除后，整个文档无法按原来的缩放关系来进行展示。

我后续尝试优化一下，但我感觉其中的逻辑可能会比预想的要复杂一些

**Comment by xiaozzzi** [comment]
该问题已在[v1.10.0](https://github.com/blossom-editor/blossom/releases/tag/v.1.10.0)版本修复
