### ISSUE TITLE
对于双链的的展示可以调整一下

### ISSUE THREAD

**Issue by w-66** [blossom-editor/blossom#24]
引用的双方可以有个显示，或许更好

**Comment by xiaozzzi** [comment]
引用的双方是指？可否再详细一些

**Comment by w-66** [comment]
![图片](https://github.com/blossom-editor/blossom/assets/55654280/a0ee010e-fa3a-4c9c-95a7-68c08190c801)
![图片](https://github.com/blossom-editor/blossom/assets/55654280/989cc7dc-4d77-4f6a-a571-261e50a342fa)

**Comment by xiaozzzi** [comment]
该功能已在 [v1.8.0](https://github.com/blossom-editor/blossom/releases/tag/v1.8.0) 版本中支持
