### ISSUE TITLE
[BUG]快捷键异常

### ISSUE THREAD

**Issue by silas-wen** [blossom-editor/blossom#25]
客户端：MacOS 1.7.0
问题：在文章页面，使用CMD+1 展开或者收缩目录栏（全程不松开CMD），不松开CMD继续按1无反应，反而按其他数字比如2，会执行CMD+1的逻辑，然后再按任何数字键都没有效果了。
希望效果：在不松开CMD的情况下继续按数字键可以按照正常逻辑执行

**Comment by xiaozzzi** [comment]
该问题已在 v1.7.2 中修复
