### ISSUE TITLE
【建议】Web端文章URI优化

### ISSUE THREAD

**Issue by silas-wen** [blossom-editor/blossom#26]
目前效果：![image](https://github.com/blossom-editor/blossom/assets/81892709/5b8eeb8c-dac3-4670-b9db-89bca49d0fd1)
Web端在已经定位到某文章的情况下，URI没有指向这篇文章，如果需要将文章分享给朋友，URL分享出去别人打开是文章的首页，而不是我希望分享的那篇文章

希望效果：URI可以定位到具体文章，或者增加一个分享按钮自动复制能够准确定位到当前文章的URL

**Comment by xiaozzzi** [comment]
该问题已在 [v1.8.0](https://github.com/blossom-editor/blossom/releases/tag/v1.8.0) 版本中修复
