### ISSUE TITLE
intel芯片的mac无法使用

### ISSUE THREAD

**Issue by Kiris-tingna** [blossom-editor/blossom#29]
提示不支持此类应用程序

**Comment by xiaozzzi** [comment]
抱歉😟，因为我手上没有 intel 芯片的 mac，所以还缺乏 intel mac 的测试，我正在尝试寻找一些其他方式解决该问题

**Comment by gclm** [comment]
我是intel 芯片，我自己已经尝试打包成功后，不知道我是否方便介入开发呢?我把这个打包测试的镜像上传一下

**Comment by xiaozzzi** [comment]
> 我是intel 芯片，我自己已经尝试打包成功后，不知道我是否方便介入开发呢?我把这个打包测试的镜像上传一下
> 
> https://f.ws59.cn/f/cuh1ogwnsns 复制链接到浏览器打开
> 
> 目前临时网盘有效期为24小时

可以呀，欢迎以任何形式加入进来开发😉

**Comment by xiaozzzi** [comment]
现阶段所有关于 Mac Intel 版本问题将整理至(#69)

**Comment by gclm** [comment]
> 文件已失效，请求分享其它网盘，感谢~

https://www.123pan.com/s/iFqbVv-k4eQA.html 提取码: uOW0
intel版本的安装包
