### ISSUE TITLE
后续是否考虑增加一个docker-compose方式进行部署

### ISSUE THREAD

**Issue by li-guohao** [blossom-editor/blossom#3]
当前的部署方式相对比较麻烦，
后续是否考虑增加一个`docker-compose`和`docker ci`方式进行部署

### docker compose
就是使用 docker compose 配置文件，直接启动进行

### docker ci
就是使用 docker run ... 进行启动容器

**Comment by li-guohao** [comment]
### docker ci

``` shell
docker run -d \
  --name blossom-dev \
  -p 9999:9999 \
  -v ~/blossom:/home/bl \
  blossom:dev \
  --spring.profiles.active=prod \
  --project.iaas.blos.domain="http://192.168.2.222:9998/bl/pic/" \
  --project.iaas.blos.default-path="/home/bl/img/" \
  --spring.datasource.url=jdbc:mysql://192.168.2.222:3306/blossom?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8 \
  --spring.datasource.username=root \
  --spring.datasource.password=123456 
```


```

**Comment by nn200433** [comment]
哈哈，我也是昨天弄得

https://gitee.com/nn200433/blossom/blob/dev/blossom-backend/Dockerfile

**Comment by li-guohao** [comment]
> 哈哈，我也是昨天弄得
> 
> 
> 
> https://gitee.com/nn200433/blossom/blob/dev/blossom-backend/Dockerfile

昨天的pr(#4)已经合并到上游了，和作者讨论后，目前不做ci自动构建镜像到dockerhub，所以镜像还得再等等，得等作者手动编译镜像上传到dockerhub。
我打算等有了镜像再部署。
dockerfile在目录 blossom-backend 里。

**Comment by fishandbread** [comment]
期待docker部署，既然离线，搞个随身wifi刷debian，部署了随身带着不用太方便。也不用多端部署
