### ISSUE TITLE
应用就只有电脑端的吗？

### ISSUE THREAD

**Issue by renshinizhenhao** [blossom-editor/blossom#32]
苹果，安卓手机端的有没有？

**Comment by xiaozzzi** [comment]
目前没有移动客户端，只有移动网页端，可以到[移动端文档](https://www.wangyunf.com/blossom-doc/guide/deploy/blog.html)看看。

**Comment by T1anjiu** [comment]
目前现有的最简单的解决方式是可以用网页打包。或者可以自写一个😂
