### ISSUE TITLE
[建议&讨论] 关于便签的优化建议

### ISSUE THREAD

**Issue by dark3212** [blossom-editor/blossom#34]
在有笔记的软件里使用便签，更多情况是快速记录一些灵感一闪、临时任务，杂七杂八暂时无法归类或者稍后整理的东西。这种场景一般要求记录的快，离开的也会很快。
所以希望便签的记录能够更加快捷化，比如有全局的快捷键直接到达便签的编辑页面，或者有桌面小插件随手记录便签。
而现在记录便签需要：
1.打开软件
2.点击note
3.鼠标挪到编辑区，点击编辑
步骤还不不太方便，希望能优化一下

**Comment by xiaozzzi** [comment]
页面和交互设计是个难点，不知有什么好的建议吗？
