### ISSUE TITLE
[讨论] 是否会增加minio的存储支持

### ISSUE THREAD

**Issue by Andecheal** [blossom-editor/blossom#46]
是否会增加minio的存储支持

**Comment by xiaozzzi** [comment]
虽然有在计划中，但是还有很多优先级更高的计划排在前面，所以没太多精力兼容其他对象存储😣

**Comment by Andecheal** [comment]
我看目前对象存储服务这块后台代码还没有完全实现,我有时间可以贡献一下相关的代码😀
