### ISSUE TITLE
群晖安装后报这个错误，请问什么问题

### ISSUE THREAD

**Issue by adl10929** [blossom-editor/blossom#49]
![微信截图_20231220140345](https://github.com/blossom-editor/blossom/assets/62693144/834fffa4-4337-468c-aedd-5255cf9f203e)

**Comment by xiaozzzi** [comment]
可以参考文档的[常见问题](https://www.wangyunf.com/blossom-doc/guide/deploy/faq.html#mariadb-not-allowed)部分。

**Comment by xiaozhubin** [comment]
就是需要把你在blossom里用的用户的主机名设置为“任意主机“、”%“。可以在phpmyadmin里手动修改，也可以用下面的语句修改：
`update user set host = '%' where user = 'root';`
那个`root`的用户，是你在blossom里用的用户名（如果你用的不是root的话）。
