### ISSUE TITLE
小屏幕笔记本电脑前端界面显示缺失

### ISSUE THREAD

**Issue by lonevle** [blossom-editor/blossom#51]
设备是14英寸的笔记本，在1080p的屏幕下，以100%大小显示是看不见主页的代办，也没有滚动条，无法下滑。

![image](https://github.com/blossom-editor/blossom/assets/48077551/bfede9a2-3b0c-498f-8291-ff8ad1e44548)

如果是全屏是可以看到的。

![image](https://github.com/blossom-editor/blossom/assets/48077551/c21533ec-81b0-4125-be38-253fa139f0f4)

**Comment by xiaozzzi** [comment]
PC客户端是适配了1080P下全屏的显示效果的，正常情况下如下图
<img width="1920" alt="9da440fc6ed6c94debd75258c326e519" src="https://github.com/blossom-editor/blossom/assets/42293085/b7d5c206-9b02-44b6-93a5-7f13cb5dcb2c">

但是网页版客户端的话，可能因为地址栏等内容占用了屏幕空间，导致无法完整显示，目前只能通过缩放页面进行调整了
