### ISSUE TITLE
【建议】MacOS系统的低版本支持

### ISSUE THREAD

**Issue by tszlfasy** [blossom-editor/blossom#53]
硬件版本：2015年Pro版本
系统版本：目前是12.7.X
处理核心：Inter

希望开发者可以考虑向下兼容一点点。
非常感谢你们开发好的软件~ 🙏🏻

**Comment by 217heidai** [comment]
同求兼容Intel处理器macOS

**Comment by xiaozzzi** [comment]
关于 inter 芯片的 mac 可查看(#29)
