### ISSUE TITLE
mvn build failed

### ISSUE THREAD

**Issue by freakishness** [blossom-editor/blossom#6]
mvn version:
>Apache Maven 3.9.4
Maven home: /usr/share/maven
Java version: 11.0.20.1, vendor: Oracle Corporation, runtime: /usr/lib64/jvm/java-11-openjdk-11
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "6.5.4-1-default", arch: "amd64", family: "unix"

error message:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project common-base: Compilation failure
[ERROR] /home/freak/Projects/blossom/blossom-backend/common/common-base/src/main/java/com/blossom/common/base/util/json/JsonUtil.java:[108,19] 对Module的引用不明确[ERROR]   com.fasterxml.jackson.databind 中的类 com.fasterxml.jackson.databind.Module 和 java.lang 中的类 java.lang.Module 都匹配[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :common-base

**Comment by nn200433** [comment]
同 maven 版本，打包没有问题

**Comment by li-guohao** [comment]
你是在子目录下运行的吗？

**Comment by li-guohao** [comment]
> 你是在子目录下运行的吗？

你可能需要在项目根目录下运行命令

**Comment by freakishness** [comment]
默认jdk版本11, pom.xml配置中的java版本没起作用。手动使用update-alternatives切换java版本到openjdk 1.8,重新编译成功，修改下编译说明吧

**Comment by freakishness** [comment]
是不是mvn版本也有要求？
mvn clean build 报错：

> [ERROR] Unknown lifecycle phase "build". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: pre-clean, clean, post-clean, validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-site, site, post-site, site-deploy. -> [Help 1]

**Comment by xiaozzzi** [comment]
目前未在linux环境下的进行过编译，这可能需要我进行一些测试，有结果后我们再来讨论👏

如果你常用linux环境进行开发的话，那你会比我熟悉很多哦，也十分欢迎你能提一些意见或者解决方案啦啦🤝
