### ISSUE TITLE
希望有个开关可以控制上传的图片是否重命名

### ISSUE THREAD

**Issue by 52lemon6** [blossom-editor/blossom#63]
希望有个开关可以控制上传的图片是否重命名，比如我用截图工具截图的图片直接粘贴的图片名字都是一样的，这样直接粘贴的话要不就是无法上传图片要不就是原先的图片被删除了，望能加一个自动重命名的上传图片的开关

**Comment by xiaozzzi** [comment]
在设置中有该功能
![image](https://github.com/blossom-editor/blossom/assets/42293085/f69675c4-a542-43d8-94ba-f6f5010859d5)
