### ISSUE TITLE
Markdown预览有问题

### ISSUE THREAD

**Issue by wangkai9799** [blossom-editor/blossom#64]
![image](https://github.com/blossom-editor/blossom/assets/34116538/fffd9cea-1925-4352-8d68-aeb3b51ad872)

在输入列表项之后，添加一个可勾选的项目，展示就有问题了

**Comment by xiaozzzi** [comment]
已在 [v1.12.0](https://github.com/blossom-editor/blossom/releases/tag/v1.12.0) 版本中修复
