### ISSUE TITLE
【bug】macos 安装出现问题

### ISSUE THREAD

**Issue by xkloveme** [blossom-editor/blossom#66]
![image](https://github.com/blossom-editor/blossom/assets/29595042/039f8baa-f599-40b3-87f8-0f3675cbe085)
![image](https://github.com/blossom-editor/blossom/assets/29595042/0dbbeac0-b953-416c-b5a2-006a34b11239)
 还有 web 密码失效时间太短了，设计长一点 一个月，或者动态 token 无感刷新

**Comment by xkloveme** [comment]
应该是缺少 inter 版本的

**Comment by xiaozzzi** [comment]
授权时长可见文档[修改授权时长](https://www.wangyunf.com/blossom-doc/guide/deploy/backend-props.html#props-auth)。

**Comment by xiaozzzi** [comment]
现阶段所有关于 Mac Intel 版本问题将整理至(#69)

**Comment by xkloveme** [comment]
> 授权时长可见文档[修改授权时长](https://www.wangyunf.com/blossom-doc/guide/deploy/backend-props.html#props-auth)。

![image](https://github.com/blossom-editor/blossom/assets/29595042/1c6a98b7-c18b-420d-8a25-446bf1dedf41)

咨询下 授权时间 使用 Docker Compose 的变量是啥，给出的示例并没有相关变量
