### ISSUE TITLE
[bug]打开新文章后，右边栏进度不置顶

### ISSUE THREAD

**Issue by HiMenma** [blossom-editor/blossom#67]
在你的博客中，看完文章1，点击文章2，文章2的进度貌似是记住了文章1的位置，没有置顶，需要手动拉到最上方。
![image](https://github.com/blossom-editor/blossom/assets/40138451/be81432e-db60-4598-9615-f66ad0ebed05)
![image](https://github.com/blossom-editor/blossom/assets/40138451/421e9557-14af-4c94-82bd-1a70bccccf9e)

**Comment by xiaozzzi** [comment]
已在 [v1.12.0](https://github.com/blossom-editor/blossom/releases/tag/v1.12.0) 版本中修复
