### ISSUE TITLE
关于 Mac Intel 版本的支持

### ISSUE THREAD

**Issue by xiaozzzi** [blossom-editor/blossom#69]
很抱歉各位😿，由于开发者没有 Intel 版本的设备，无法进行充分的测试，所以暂时没有 Intel 版本的客户端安装包。

目前可以选择使用后台自带的 Web 版客户端，具体内容可见[《网页版客户端文档》](https://www.wangyunf.com/blossom-doc/guide/deploy/client.html)。

**Comment by gclm** [comment]
https://www.123pan.com/s/iFqbVv-k4eQA.html提取码:uOW0
intel版本的安装包

**Comment by gclm** [comment]
intel 最新dev 分支打包失败。
![image](https://github.com/blossom-editor/blossom/assets/27618687/d7a1546b-4377-44e6-9edb-06d5f73e7d13)
