### ISSUE TITLE
试用账号登录报错

### ISSUE THREAD

**Issue by hangboss1761** [blossom-editor/blossom#7]
![image](https://github.com/blossom-editor/blossom/assets/30379896/b10b21dd-8d93-41a3-b0d9-8d2b5198f176)

**Comment by xiaozzzi** [comment]
这个问题我怀疑是有人在试用时修改了密码，这个我稍晚些会将密码还原，抱歉😵

**Comment by xiaozzzi** [comment]
该问题已修复，请尝试重新登陆
