### ISSUE TITLE
咨询一下，数据在docker里的保存格式

### ISSUE THREAD

**Issue by xh542428798** [blossom-editor/blossom#71]
感谢大佬用爱发电，想问一下，blossom在docker的数据保存格式是md格式吗，我是否可以把windows上的obsidian的md同步到docker的文件夹下，这样就可以让docker的数据和本地的md数据保持同步？

**Comment by xiaozzzi** [comment]
文章是保存在数据库的，所以是没法映射 md 文件的，抱歉
