### ISSUE TITLE
优化建议-todo里面增加deadline 截至日期

### ISSUE THREAD

**Issue by huzhujiang2014** [blossom-editor/blossom#75]
![image](https://github.com/blossom-editor/blossom/assets/31272948/252c6983-e841-4062-85fd-0d2d116be519)
在plan里面新增的时候这个时间提示hover是日期、还是容易影响

还有是否能在todo里面增加代办时可以设置一个要求截至日期、在加上根据离截止日期还剩多少天来 展示不同的颜色（角标也行）

同时是否支持接入短信/邮件等通知平台、支持plan到期/点 提示

**Comment by xiaozzzi** [comment]
感谢反馈！
1. plan 确实是 placeholder 中有歧义，下版本修复。
2. todo 是有截止日期的，但不是日期的形式。因为不是日期所以也很难做倒计时和到期提示。
3. 短信因为是收费的，所以 Blossom 肯定无法提供该服务了。邮件的配置对于用户来说可能略微复杂，可能会在未来版本支持，但可能不会支持 todo 的到期提示。
