### ISSUE TITLE
[建议&讨论] 建议增加多级菜单的层级和导入新图标

### ISSUE THREAD

**Issue by Chang-Tao** [blossom-editor/blossom#79]
我在记录分类文档资料时会用到多级菜单, 目前创建的菜单层级最大是4级. 希望能增加一些.
然后就是图标, 现有图标库的工作方式非常喜欢,但是感觉还缺少一些, 我平时做虚拟化,服务器系统运维和网站域名管理,希望能够支持自定义上传一些图标,这样可以上传一些自己喜欢的图标,格式规则还是跟图标库一样.
当然是在不影响作者大大自己开发计划的情况下小小的考虑一下.

**Comment by xiaozzzi** [comment]
谢谢反馈！
1. 菜单层级应该未来的计划中会优化。
2. 图标是可以填写图片地址的，可以把自己需要的logo上传到照片墙中，然后把地址复制到图标框中就行，只需要注意一下图片大小，过大的图片可能会加载缓慢和造成卡顿

比方说试用账号中的图标就是图片
![image](https://github.com/blossom-editor/blossom/assets/42293085/8802230f-eee5-464b-a588-d52d3f44477d)
