### ISSUE TITLE
检索bug

### ISSUE THREAD

**Issue by pixb** [blossom-editor/blossom#81]
# 文章的内容
```
# test


## 这个测试文章
1111
2222

## 222
222
```
我检索222可以搜到
![image](https://github.com/blossom-editor/blossom/assets/7930398/92c74a03-2dcd-499c-b3b2-dcdcdc6f955c)
但是检索111搜不到
![image](https://github.com/blossom-editor/blossom/assets/7930398/678a7b48-4486-4e6c-bf40-02bf2d7b7ee8)

**Comment by Andecheal** [comment]
1111可以搜索到吗
