### ISSUE TITLE
【建议】设置页面跳转

### ISSUE THREAD

**Issue by klaus-cicd** [blossom-editor/blossom#82]
在已登录状态下，点击左下角设置按钮后，希望直接跳转到设置页面，而不是登录页面。
<img width="340" alt="image" src="https://github.com/blossom-editor/blossom/assets/81892709/c5874103-baff-4fb6-961f-9587a6488c64">

**Comment by xiaozzzi** [comment]
该功能已在 [v1.13.0](https://github.com/blossom-editor/blossom/releases/tag/v1.13.0) 版本中发布
