### ISSUE TITLE
支持obsidian导入或者编辑吗

### ISSUE THREAD

**Issue by Ice-chen** [blossom-editor/blossom#84]
可以支持导入obsidian的所有文件及层级目录吗？
可以支持obsidian直接读取、编辑笔记吗？

**Comment by xiaozzzi** [comment]
目前不支持

**Comment by Ice-chen** [comment]
未来有计划支持吗？如果可以支持的话其实可以节省更换工具的上手成本，目前个人使用的方案是通过NAS实现同步obsidian，然后在内网使用了 Quartz 的服务构建了自有的数字花园，但 Quartz 的缺点就是无法在线编辑，在看到 blossom 后觉得很符合需求，但是考虑到更换成本的问题，想确认一下有没有无痛的方式切换^-^
