### ISSUE TITLE
【反馈】在Safari 浏览器上使用时，会出现一些问题

### ISSUE THREAD

**Issue by ruluer** [blossom-editor/blossom#86]
1. todo的任务无法在不同阶段拖动
    - Mac上的Safari会出现此问题，但Chrome/Edge不会
    - iOS/iPad OS所有的浏览器都会出现此问题
2. 博客端无法通过连续点击7次图标登陆
    - iOS/iPad OS所有浏览器均如此
3. todo里的任务无法通过双击标题栏和内容进行快速修改
    - iOS/iPad OS所有浏览器均如此

**Comment by T1anjiu** [comment]
在Mac客户端中会有这样的问题吗，在有客户端的情况下，我们还是建议用户先使用客户端 ：）

对于Mac的Safari浏览器出现的问题，能否附带上图片和日志呢，这样可以更好的方便我们定位问题😊

对于iOS / iPad OS下的浏览器问题，您可以查看#94 来获取更加详细的解释

感谢您的支持！

**Comment by xiaozzzi** [comment]
该问题已在[v1.14.0](https://github.com/blossom-editor/blossom/releases/tag/v1.14.0)版本中修复。
