### ISSUE TITLE
ios网页打开会一直处于加载中

### ISSUE THREAD

**Issue by sitieqiang** [blossom-editor/blossom#91]
打开你的在线地址也是一样的https://www.wangyunf.com/blossom-demo/#/settingindex
![微信图片_20240227150150](https://github.com/blossom-editor/blossom/assets/42805344/5496b9aa-da74-406f-997d-9d745d8ca4ee)

**Comment by sitieqiang** [comment]
具体还需要什么log我可以提供

**Comment by xiaozzzi** [comment]
客户端不支持移动端

**Comment by sitieqiang** [comment]
哦 那是我理解错了 是只有博客支持移动端的   你有计划在移动端实现一下这个吗

**Comment by xiaozzzi** [comment]
客户端是为PC设计的，未来应该不会兼容移动端。
移动端博客可以登录后进行计划，待办，便签的增删改操作，但不能编写文章。
