### ISSUE TITLE
[建议&讨论] 能否在编辑器置顶的工具栏中，加入字体、字号、标题等快捷菜单？谢谢

### ISSUE THREAD

**Issue by renyuan431** [blossom-editor/blossom#95]
功能建议：能否在编辑器置顶的工具栏中，加入字体、字号、几级标题等快捷菜单？
不知道是否有这个考虑，谢谢

**Comment by xiaozzzi** [comment]
markdown 不支持字体字号，所以应该不会增加

标题的菜单可以增加，但感觉实际用起来不如按 `#` 号键来的快捷方便

**Comment by renyuan431** [comment]
> markdown 不支持字体字号，所以应该不会增加
> 
> 标题的菜单可以增加，但感觉实际用起来不如按 `#` 号键来的快捷方便

多谢回复，麻烦了
