### ISSUE TITLE
[功能需求] 对预览界面复制为微信文章或者知乎文章？

### ISSUE THREAD

**Issue by xh542428798** [blossom-editor/blossom#96]
我有自己的公众号，不知道是否可以增强功能，对预览界面复制为微信文章或者知乎文章？

**Comment by xiaozzzi** [comment]
不知微信和知乎是否支持 markdown，或者他们具体支持使用什么格式？

**Comment by T1anjiu** [comment]
> 不知微信和知乎是否支持 markdown，或者他们具体支持使用什么格式？

知乎支持Markdown的
