### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by roadinger** [blossom-editor/blossom#97]
菜单调成中文
支持其它博客文章一键保存

**Comment by xiaozzzi** [comment]
1. 未来支持多语言时会调整成中文
2. 没太明白，能否再具体说明一下

**Comment by roadinger** [comment]
一键收录其它网站的文章，搞个浏览器插件

**Comment by roadinger** [comment]
还有整体界面  能否出个扁平化的主题，不要花里胡哨的，简约清爽的

**Comment by xiaozzzi** [comment]
> 一键收录其它网站的文章，搞个浏览器插件

目前不会，可以借助其他插件保存成本地md再上传到blossom

**Comment by xiaozzzi** [comment]
> 还有整体界面 能否出个扁平化的主题，不要花里胡哨的，简约清爽的

右上角可以调整主题和页面样式，如下图，如果不满意可以尝试其他应用
![image](https://github.com/blossom-editor/blossom/assets/42293085/d604d2ff-2da8-4423-988d-7df41036a465)
