### ISSUE TITLE
有没有ubuntu版本的，我们的服务都是部署在linux的，我们日常也使用ubuntu，属实用不了，只能用docker了

### ISSUE THREAD

**Issue by cxh0806** [blossom-editor/blossom#99]

**Comment by xiaozzzi** [comment]
你是指在linux部署后台，还是在linux安装桌面客户端？后台可以在任何系统中部署，不是只能部署在docker中。

桌面客户端暂时在linux安装，不过后台自带网页版的客户端，可以通过浏览器访问
